[package]
name = "anitrack"
version = "0.1.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[profile.release]
lto = true

[dependencies]
base64       = "0.9"
chrono       = "0.4"
clap         = "2.29"
failure      = "0.1"
lazy_static  = "1.0"
regex        = "0.2"
serde        = "1.0"
serde_derive = "1.0"
serde_json   = "1.0"
toml         = "0.4"

[dependencies.mal]
version = "0.5"
default-features = false

features = ["anime-list"]