[package]
name = "anitrack"
version = "0.1.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[lib]
name = "mal"
path = "src/libmal/lib.rs"

[[bin]]
name = "anitrack"
path = "src/bin/main.rs"
doc  = false

[dependencies]
