[package]
name = "anitrack"
version = "0.1.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[lib]
name = "mal"
path = "src/libmal/lib.rs"

[[bin]]
name = "anitrack"
path = "src/bin/main.rs"
doc  = false

[dependencies]
failure        = "0.1"
failure_derive = "0.1"
lazy_static    = "0.2"
regex          = "0.2"
reqwest        = "0.8"
minidom        = "0.6"
chrono         = "0.4"