[package]
name = "anup"
version = "0.1.0"
authors = ["Acizza <jonathanmce@pm.me>"]
build = "build.rs"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
base64       = "0.10"
chrono       = { version = "0.4", features = ["serde"] }
clap         = "2"
failure      = "0.1"
directories  = "1"
lazy_static  = "1"
regex        = "1"
reqwest      = "0.9"
serde        = "1"
serde_derive = "1"
serde_json   = "1"
toml         = "0.4"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["shellapi", "synchapi"]