[package]
name = "anitrack"
version = "0.1.0"
authors = ["Acizza <jonathanmce@gmail.com>"]

[dependencies]
regex            = "0.2.*"
lazy_static      = "0.2.*"
hyper            = "0.10.*"
hyper-native-tls = "0.2.*"
rquery           = "0.3.*"
error-chain      = "0.10.*"