[package]
name = "anup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"
default-run = "anup"

[dependencies]
dirs = "~2.0.0"
gumdrop = "~0.8.0"
once_cell = "~1.4.0"
termion = "~1.5.0"
toml = "~0.5.0"
tui = "~0.9.0"
regex = "~1.3.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~1.4.0"
strsim = "~0.10.0"
unicode-width = "~0.1.0"

[dependencies.anime]
path = "../anime"
features = [ "diesel-support" ]

[dependencies.chrono]
version = "~0.4.0"
features = [ "serde" ]

[dependencies.diesel]
version = "~1.4.0"
default-features = false
features = [ "sqlite", "chrono" ]

[dependencies.snafu]
version = "~0.6.0"
features = [ "backtraces" ]