[package]
name = "anup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"
default-run = "anup"

[dependencies]
chrono = "~0.4.0"
dirs-next = "~1.0.0"
gumdrop = "~0.8.0"
once_cell = "~1.4.0"
termion = "~1.5.0"
toml = "~0.5.0"
# Pinned until version 0.10 so we can use this feature: https://github.com/fdehau/tui-rs/pull/309
tui = { git = "https://github.com/fdehau/tui-rs", rev = "8c2ee0ed8516be887f5f68355c325fadecb5d2dc" }
regex = "~1.3.0"
rmp-serde = "~0.14.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~1.4.0"
strsim = "~0.10.0"
unicode-width = "~0.1.0"

[dependencies.anime]
path = "../anime"
features = [ "diesel-support", "chrono-support" ]

[dependencies.diesel]
version = "~1.4.0"
default-features = false
features = [ "sqlite" ]

[dependencies.snafu]
version = "~0.6.0"
features = [ "backtraces" ]