[package]
name = "anup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
anime = { path = "../anime" }
dirs = "~2.0.0"
lazy_static = "~1.4.0"
termion = "~1.5.0"
toml = "~0.5.0"
tui = "~0.6.0"
regex = "~1.3.0"
rmp-serde = "~0.14.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~1.0.0"
strsim = "~0.9.0"

[dependencies.chrono]
version = "~0.4.0"
features = [ "serde" ]

[dependencies.clap]
version = "~2.33.0"
default_features = false
features = [ "vec_map" ]

[dependencies.snafu]
version = "~0.6.0"
features = [ "backtraces" ]