[package]
name = "anup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"
default-run = "anup"

[dependencies]
detect = { path = "../detect" }
dirs = "~2.0.0"
once_cell = "~1.2.0"
termion = "~1.5.0"
toml = "~0.5.0"
tui = "~0.8.0"
regex = "~1.3.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~1.1.0"
strsim = "~0.9.0"
unicode-width = "~0.1.0"

[dependencies.anime]
path = "../anime"
features = [ "rusqlite-support" ]

[dependencies.chrono]
version = "~0.4.0"
features = [ "serde" ]

[dependencies.clap]
version = "~2.33.0"
default_features = false
features = [ "vec_map" ]

[dependencies.rusqlite]
version = "~0.21.0"
features = [ "chrono" ]

[dependencies.snafu]
version = "~0.6.0"
features = [ "backtraces" ]