[package]
name = "anup"
version = "0.0.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"
default-run = "anup"

[dependencies]
anyhow = "~1.0.0"
bincode = "~1.3.0"
chrono = "~0.4.0"
dirs-next = "~1.0.0"
once_cell = "~1.4.0"
termion = "~1.5.0"
thiserror = "~1.0.0"
toml = "~0.5.0"
# Pinned until version 0.10 so we can use this feature: https://github.com/fdehau/tui-rs/pull/309
tui = { git = "https://github.com/fdehau/tui-rs", rev = "8c2ee0ed8516be887f5f68355c325fadecb5d2dc" }
serde = "~1.0.0"
serde_derive = "~1.0.0"
smallvec = "~1.4.0"
strsim = "~0.10.0"
unicode-segmentation = "~1.6.0"
unicode-width = "~0.1.0"

[dependencies.anime]
path = "../anime"
features = [ "diesel-support", "chrono-support" ]

[dependencies.diesel]
version = "~1.4.0"
default-features = false
features = [ "sqlite" ]

[dependencies.pico-args]
version = "~0.3.0"
default-features = false