[package]
name = "detect"
version = "0.1.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
anime = { path = "../anime" }
lazy_static = "~1.4.0"
regex = "~1.3.0"
snafu = "~0.6.0"
strsim = "~0.9.0"