[package]
name = "anime"
version = "0.1.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
base64 = "~0.11.0"
once_cell = "~1.3.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
serde_json = "~1.0.0"
regex = "~1.3.0"
snafu = "~0.6.0"

[dependencies.chrono]
version = "~0.4.0"
features = [ "serde" ]

[dependencies.diesel]
version = "~1.4.0"
optional = true
default-features = false
features = [ "sqlite" ]

[dependencies.ureq]
version = "~0.11.0"
features = [ "json" ]

[features]
default = []
print-requests-debug = []
diesel-support = [ "diesel" ]