[package]
name = "anime"
version = "0.1.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
base64 = "~0.10.0"
hashbrown = "~0.5.0"
lazy_static = "~1.3.0"
serde = "~1.0.0"
serde_derive = "~1.0.0"
serde_json = "~1.0.0"
regex = "~1.2.0"
reqwest = "~0.9.0"
snafu = "~0.4.0"

[dependencies.chrono]
version = "~0.4.0"
features = [ "serde" ]

[features]
default = []
print-requests-debug = []
