[package]
name = "anisplit"
version = "0.1.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
anime = { path = "../anime" }
detect = { path = "../detect" }
gumdrop = "~0.8.0"
snafu = "~0.6.0"