name: release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Rust version
      run: |
        rustc --version
        cargo --version

      - name: Build release binary
        run: cargo build --release

      - name: Package release artifact
        run: |
          cd target/release
          strip ./anup
          zip anup-linux.zip -xi ./anup

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Get release version number
        id: get_version
        uses: battila7/get-version-action@v2
        
      - name: Upload release artifact
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/anup-linux.zip
          asset_name: anup-linux-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip
